const nodeCrypto=require('node:crypto');
const {getAddress,verifyMessage,parseUnits}=require('ethers');

function normalizeTokenGate(input){
 if(!input?.enabled)return {enabled:false};const type=input.type;if(!['erc20','erc721'].includes(type))throw new Error('Token gate 類型不正確。');let contract;try{contract=getAddress(String(input.contract||''));}catch{throw new Error('Token gate 合約地址不正確。');}const name=String(input.name||'Token holder').trim();if(!name||name.length>120)throw new Error('Token gate 名稱需為 1–120 字。');const decimals=type==='erc20'?Number(input.decimals):0,minimum=type==='erc20'?String(input.minimum||'1'):'1';try{if(type==='erc20'&&(!Number.isInteger(decimals)||decimals<0||decimals>36||minimum.length>80||!/^(0|[1-9]\d*)(\.\d+)?$/.test(minimum)||parseUnits(minimum,decimals)<=0n))throw Error();}catch{throw new Error('ERC-20 最低持有量或小數位不正確。');}return {enabled:true,type,contract,name,minimum,decimals};
}
const challengeMessage=({event,chain='ethereum',address,nonce})=>`言文字活動報名\nEvent: ${event}\nChain: ${chain}\nWallet: ${address}\nNonce: ${nonce}`;
function ethereumAddress(value){try{return getAddress(String(value||''));}catch{throw new Error('Ethereum 錢包地址不正確。');}}
function base58(value){const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const char of String(value||'')){const digit=alphabet.indexOf(char);if(digit<0)throw Error();n=n*58n+BigInt(digit);}const bytes=[];while(n){bytes.unshift(Number(n&255n));n>>=8n;}for(const char of String(value||'')){if(char!=='1')break;bytes.unshift(0);}return Buffer.from(bytes);}
function solanaAddress(value){const address=String(value||'').trim();try{if(base58(address).length!==32)throw Error();}catch{throw new Error('Solana 錢包地址不正確。');}return address;}
function verifyEthereum({token,signature},event,verifyToken){
 const proof=verifyToken(String(token||''),{purpose:'oauth'});if(!proof||proof.p!=='event-crypto'||proof.e!==event||proof.c!=='ethereum')throw new Error('錢包驗證已失效，請重新連接。');let recovered;try{recovered=getAddress(verifyMessage(challengeMessage({event,chain:proof.c,address:proof.a,nonce:proof.n}),String(signature||'')));}catch{throw new Error('錢包簽名不正確。');}if(recovered!==proof.a)throw new Error('錢包簽名與地址不符。');return {chain:'ethereum',address:proof.a};
}
function verifySolana({token,signature},event,verifyToken){const proof=verifyToken(String(token||''),{purpose:'oauth'});if(!proof||proof.p!=='event-crypto'||proof.e!==event||proof.c!=='solana')throw new Error('錢包驗證已失效，請重新連接。');let valid=false;try{const key=nodeCrypto.createPublicKey({key:Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),base58(proof.a)]),format:'der',type:'spki'});valid=nodeCrypto.verify(null,Buffer.from(challengeMessage({event,chain:proof.c,address:proof.a,nonce:proof.n})),key,Buffer.from(String(signature||''),'base64'));}catch{}if(!valid)throw new Error('Solana 錢包簽名不正確。');return {chain:'solana',address:proof.a};}
async function tokenBalance(gate,address,rpcUrl,tokenId){
 if(!rpcUrl)throw Object.assign(Error('Ethereum RPC 尚未設定。'),{status:503});let data;if(gate.type==='erc721'){if(typeof tokenId!=='string'||!/^(0|[1-9]\d{0,77})$/.test(tokenId)||BigInt(tokenId)>2n**256n-1n)throw Error('請填寫有效的 NFT Token ID。');data='0x6352211e'+BigInt(tokenId).toString(16).padStart(64,'0');}else data='0x70a08231'+address.slice(2).toLowerCase().padStart(64,'0');let response;try{response=await fetch(rpcUrl,{signal:AbortSignal.timeout(10000),method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_call',params:[{to:gate.contract,data},'latest']})});}catch{throw Object.assign(Error('目前無法驗證 Token 持有資格。'),{status:502});}const result=await response.json().catch(()=>({}));if(!response.ok||typeof result.result!=='string'||!/^0x[0-9a-f]+$/i.test(result.result))throw Object.assign(Error('目前無法驗證 Token 持有資格。'),{status:502});if(gate.type==='erc721')return {eligible:result.result.slice(-40).toLowerCase()===address.slice(2).toLowerCase(),token_id:tokenId};const balance=BigInt(result.result),minimum=parseUnits(gate.minimum,gate.decimals);return {eligible:balance>=minimum,balance:balance.toString()};
}
module.exports={normalizeTokenGate,challengeMessage,ethereumAddress,solanaAddress,verifyEthereum,verifySolana,tokenBalance};
